apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
type: Opaque
data:
  api_key: c3VwZXJzZWNyZXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: kubeshop/order:v1
        env:
        - name: PAYMENT_KEY
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: api_key
