apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: kubeshop/order:v1
        volumeMounts:
        - name: data-vol
          mountPath: /var/log
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: task-pv-claim
