apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeshop-ingress
spec:
  rules:
  - host: kubeshop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: catalog-service
            port:
              number: 80
