apiVersion: v1
kind: Pod
metadata:
  name: catalog-sidecar
  labels:
    app: catalog
spec:
  containers:
  - name: catalog
    image: kubeshop/catalog:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
  
  # Add the sidecar container below
  - name: sidecar
    image: ???
    command: ???
