apiVersion: v1
kind: Pod
metadata:
  name: catalog-sidecar
  labels:
    app: catalog
spec:
  containers:
  - name: catalog
    image: kubeshop/catalog:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    
  - name: sidecar
    image: busybox
    command: ["sh", "-c", "while true; do wget -q -O- localhost:8080/health; sleep 5; done"]
